n_repetitions: 1
#num_timesteps: 100000
num_timesteps: 5000
max_episode_length: 10

# Evaluation parameters
evaluate_during_training: False
steps_between_evaluation: 100000
num_eval_episodes: 10000

# Curriculum learning parameters
curriculum_start_error_rate: 0.001
curriculum_end_error_rate: 0.05
curriculum_start_weight: 1
curriculum_end_weight: 5
curriculum_warmup_steps: 25000

# Logging parameters for Weights & Biases
wandb_logging: True
wandb_project: "rl-for-qec"