n_repetitions: 1
num_timesteps: 5000
max_episode_length: 10

# Evaluation parameters
evaluate_during_training: False
steps_between_evaluation: 100000
num_eval_episodes: 10000

# Curriculum learning parameters
curriculum_start_error_rate: 0.001
curriculum_end_error_rate: 0.05
curriculum_start_weight: 1
curriculum_end_weight: 5
curriculum_warmup_steps: 25000

# MoE training parameters
moe_num_timesteps: 1000
moe_start_p: 0.15
moe_end_p: 0.05
moe_time_penalty_factor: 100

# Logging parameters for Weights & Biases
wandb_logging: True
wandb_project: "rl-for-qec"